# Generated by Django 3.2 on 2022-03-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogSystem', '0002_auto_20220331_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='user/'),
        ),
    ]
