# Generated by Django 3.2 on 2022-03-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogSystem', '0003_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='article/'),
        ),
    ]
